### PR TITLE
fix: image load jumping

### LINKED ISSUE #404: Image load jumping
The current implementation of `Img.jsx` causes images to be replaced by a `div` anytime they are not in view (`if (!inView) return <div {...rest} ref={ref} />;`) . This may make sense for initial load, but I question whether it makes sense to remove an already loaded image. Furthermore, because the usages of `Img` do not have set height/widths the UI jumps around when the image is added/removed.

Proposed changes
* [ ] lazy load the images in a way that doesn't remove them after they've been loaded
* [ ] maintain the site flow when images are lazy loaded

**Dev Notes**
Consider #397

### PR DESCRIPTION
**Pull request by tborres**
The website appears to jump as the user scrolls down and up because the
image pop in and out as they leave the view (and the replacement doesn't
retain the size). This PR removes the inview logic as a temporary
solution to improving the usability. We'll want to consider rewriting
the logic (per #397) to improve the load times.

Closes #404

### CODE REVIEW

File: src/util/helpers.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ const renameKeys = (obj, pairs = []) =>
   }, obj);
 
 const supportsWebp = memoize(() => {
-  if (isUndefined(window)) return false;
+  if (typeof window === 'undefined') return false;
```
Comment (mewdriller) [inline src/util/helpers.js]: 🤔 Is this to reduce bundle size?

File: src/components/atoms/Img.jsx [hunk 2]
```diff
@@ -13,40 +12,23 @@ const srcProps = obj =>
   );
 
 function Img({ alt, resolutions, sizes, ...rest }) {
-  return (
-    <Observer>
```
Comment (mewdriller) [inline src/components/atoms/Img.jsx]: ⚠️ Removing the `<Observer>` code here will have perf implications as all of the images will load immediately instead of waiting until they're scrolled into view. 

We're not currently leveraging `gatsby-image` at all in this component. Previously that had been done because it was not quite baked and ready, but that's no longer the case.

There are a lot of potential performance improvements we'll get "for free" by using that component effectively.

File: src/util/helpers.js (hunk 1 above)
Comment (tborres) [reply src/util/helpers.js]: `isUndefined` doesn't work when doing `npm run build` (after removing the `Img` `InView` logic. The `typeof` approach is in line with Gatsby's [documentation](https://www.gatsbyjs.org/docs/debugging-html-builds/).

File: src/components/atoms/Img.jsx (hunk 2 above)
Comment (tborres) [reply src/components/atoms/Img.jsx]: I assumed that there would be performance implications, but honestly I think that the usability jumpiness outweighs the performance implication. I had run light house and didn't notice significant differences, but honestly I'm not that familiar with the reports. I had looked into `gatsby-image`, but I'm too unfamiliar with Gatsby, images, and our current image approach to put it in place.

**Comment by tborres** [comment]
@mewdriller are these polyfill changes kosher? If so then I think that this is ready to merge.

**Comment by mewdriller** [comment]
I would back out the await/import change for now unless you tested. I think I might have a better long-term option with a plugin. But removing the IntersectionObserver polyfill is perfect.

File: src/util/helpers.js (hunk 1 above)
Comment (mewdriller) [reply src/util/helpers.js]: 🤔 That's _super_ weird as [`_.isUndefined()`](https://github.com/b2io/base2.io/pull/407#issuecomment-499221561) is essentially exactly those lines of code. Are any of the other imports from `lodash` breaking? That seems odd that only this one would.

Comment (tborres) [reply src/util/helpers.js]: I don't understand it either. We had run into this issue previously in the `GlobalNavigation.jsx` and switching to the verbatim approach worked there too.
