### PR TITLE
(fix) 214 Contact Us Text Center IE

### LINKED ISSUE #214: Text in contact section not centered in IE
The line "Thanks to satellites and the internet, we can work with you wherever you are." is not centered in IE.

ie centering issue

For reference, the correct appearance can be viewed here:
https://www.figma.com/file/yfECZFxj1aZBSxKk4q523K/BaseTwo-Contact-Page

### PR DESCRIPTION
**Pull request by MLKendall**
Added widths to LocationTagline and ScollButton

Although dealing with widths, may be related to known IE flexbox bug:
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

Closes #214 and #215

### CODE REVIEW

File: src/components/organisms/contact/ContactHeader.jsx [hunk 1]
```diff
@@ -73,6 +73,7 @@ const LocationText = styled.span`
 const LocationTagline = styled.p`
   font-style: italic;
   margin: 0 auto 2em;
+  width: 100%;
```
Comment (csteinert) [inline src/components/organisms/contact/ContactHeader.jsx]: Alphabetical order of properties pls (we should be linting for that if we're not, I'll look into it)

**Comment by csteinert** [comment]
Looks like we lost the alignment on the scroll icon: 
screenshot 2018-01-11 11 25 24

File: src/components/organisms/contact/ContactHeader.jsx (hunk 1 above)
Comment (MLKendall) [reply src/components/organisms/contact/ContactHeader.jsx]: This is actually for the alignment comment (Github won't let me comment there)

On my IE, the alignment is correct.  I asked Kim for a third check, because I don't know if the difference is with me or with browserstack.

ie check
