### PR TITLE
fix(nav) Mobile Contact Buttons Safari Android

### LINKED ISSUE #257: Mobile Navigation Buttons Covered by Bottom Menu
The buttons at the bottom of the mobile navigation menu are covered by menus at the bottom of the screen in Safari and on Android.

Devices Tested: iPhone SE (Safari) and Google Pixel (Chrome)

### PR DESCRIPTION
**Pull request by MLKendall**
Closes #257

### CODE REVIEW

File: src/components/molecules/GlobalNavigation.jsx [hunk 1]
```diff
@@ -176,6 +176,7 @@ const ContactCallToActionContainer = styled.div`
   display: flex;
   justify-content: space-around;
   width: 100%;
+  margin-bottom: 75px;
```
Comment (csteinert) [inline src/components/molecules/GlobalNavigation.jsx]: Can we use the `em` function here, or make it a named const so we know why it's here (and not just some magic number)?

**Comment by MLKendall** [comment]
Closes #272
