### PR TITLE
fix: ie11 image not appearing

### LINKED ISSUE #418: IE11 image not appearing
The blue astronaut on the Jobs page header is not displaying in IE11. It appears that IE11 is showing as accepting webp files, but it isn't displaying the image.

image

### PR DESCRIPTION
**Pull request by tborres**
Went with the straightforward path of just using the png image rather
than trying the webp.

Closes #418

### CODE REVIEW

File: src/components/organisms/jobs/JobsHeader.jsx [hunk 1]
```diff
@@ -91,15 +90,11 @@ const JobsButton = styled(A)`
...
-const astronautSource = supportsWebp
-  ? `/img/jobs/BlueAstronaut.webp`
-  : '/img/jobs/BlueAstronaut.png';
-
 function JobsHeader({ small }) {
   return (
     <StyledHeader>
       <AstronautImg
-        src={astronautSource}
+        src="/img/jobs/BlueAstronaut.png"
```
Comment (mewdriller) [inline src/components/organisms/jobs/JobsHeader.jsx]: 🤔 Ideally we'd be leveraging something like `gatsby-image` to do the heavy lifting on the image optimization for us. This will definitely work until we get that wider image support landed.

Comment (tborres) [reply src/components/organisms/jobs/JobsHeader.jsx]: For reference: #397
